name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main
      - development

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages (Main)
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .  # Deploy the root directory

      - name: Deploy to GitHub Pages (Development)
        if: github.ref == 'refs/heads/development'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: development
          folder: .  # Deploy the root directory
          target: development

